name: TimeLimitedBan
version: 1.0.0
api: [1.12.0]
author: beito
description: 時間制限を付けてBanできます
main: beito\TimeLimitedBan\MainClass
commands:
  tban:
    description: "時間制限を付けてBanします"
    usage: "/tban <プレーヤー名> <時間(分)> [理由]"
    permission: "tban.command.tban"
  tban-ip:
    description: "時間制限を付けてIPBanします"
    usage: "/tban-ip <プレーヤー名|IPアドレス> <時間(分)> [理由]"
    permission: "tban.command.tbanip"
permissions:
  tban:
    default: op
    description: "BanLimitedTimeのすべての機能を使用することができます"
    children:
     tban.command:
       default: op
       description: "BanLimitedTimeのすべてのコマンドを使用することができます"
       children:
        tban.command.tban:
          default: op
          description: "/tbanを使用できるようになります"
        tban.command.tbanip:
          default: op
          description: "/tban-ipを使用できるようになります"